name: CI
on:
  workflow_dispatch:
jobs:
  download-model:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download tiny ggml model
      run: |
        git submodule update --init
        ./download-test-model.sh
    - name: Artifact linux x86-64
      uses: actions/upload-artifact@v4
      with:
        name: tiny-ggml-model
        path: ggml-tiny.bin
        retention-days: 2

  build-lib-linux-x86-64:
    needs: [download-model]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Setup project dir
        run: |
          mv ./tiny-ggml-model/ggml-tiny.bin ./ggml-tiny.bin
          mkdir -p dist
      - name: Build native library
        run: |
          docker build --build-arg="RUN_TESTS=true" -f dockerfile . -t whisperjni_binary:x86-64 --load
          docker run --platform=amd64 -v $(pwd)/dist:/out whisperjni_binary:x86-64 bash -c "cp src/main/resources/linux-x86-64/* /out/"
      - name: Artifact linux x86-64
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary-x86-64
          path: dist/*

  build-lib-linux-aarch64:
    needs: [download-model]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Setup project dir
        run: |
          mv ./tiny-ggml-model/ggml-tiny.bin ./ggml-tiny.bin
          mkdir -p dist
      - name: Build native library
        run: |
          docker build -f dockerfile . -t whisperjni_binary:aarch64 --platform arm64 --load
          DOCKER_BUILDKIT=1 docker run --platform=arm64 -v $(pwd)/dist:/out whisperjni_binary:aarch64 bash -c "cp src/main/resources/linux-aarch64/* /out/"
      - name: Artifact linux aarch64
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary-aarch64
          path: dist/*

  build-lib-windows:
    needs: [download-model]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # - name: Set up Maven
      #   uses: stCarolas/setup-maven@v4.5
      #   with:
      #     maven-version: 3.9.2
      - name: Setup project dir
        run: |
          git submodule update --init
          mv ./tiny-ggml-model/ggml-tiny.bin ./ggml-tiny.bin
          mkdir dist
      - name: Build native library
        shell: powershell
        run: |
          .\build_win.ps1
          # mvn test
          mv src\main\resources\win-x86-64\*.dll .\dist\
      - name: Artifact windows x86-64
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary-x86-64
          path: dist/*.dll

  build-lib-mac-x86-64:
    needs: [download-model]
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # - name: Set up Maven
      #   uses: stCarolas/setup-maven@v4.5
      #   with:
      #     maven-version: 3.9.2
      - name: Setup project dir
        run: |
          export DYLD_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/
          mkdir -p dist
          mkdir -p dist_aarch64
          git submodule update --init
          mv ./tiny-ggml-model/ggml-tiny.bin ./ggml-tiny.bin
      - name: Build binary
        run: |
          export DYLD_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/
          ./build_macos.sh x86-64
          # mvn test
          mv src/main/resources/mac-x86-64/*.dylib dist/
      - name: Artifact macos x86-64
        uses: actions/upload-artifact@v4
        with:
          name: mac-binary-x86-64
          path: dist/*.dylib
  
  build-lib-mac-aarch64:
    needs: [download-model]
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # - name: Set up Maven
      #   uses: stCarolas/setup-maven@v4.5
      #   with:
      #     maven-version: 3.9.2
      - name: Setup project dir
        run: |
          export DYLD_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/
          mkdir -p dist
          mkdir -p dist_aarch64
          git submodule update --init
          mv ./tiny-ggml-model/ggml-tiny.bin ./ggml-tiny.bin
      - name: Build binary
        run: |
          export DYLD_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/
          ./build_macos.sh aarch64
          # mvn test
          mv src/main/resources/mac-aarch64/*.dylib dist_aarch64/
      - name: Artifact macos aarch64
        uses: actions/upload-artifact@v4
        with:
          name: mac-binary-aarch64
          path: dist_aarch64/*.dylib

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-lib-linux-x86-64,build-lib-linux-aarch64,build-lib-windows,build-lib-mac-x86-64, build-lib-mac-aarch64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
    - name: check tree
      run: ls -R
    - name: setup resources
      run: |
        mv ./linux-binary-x86-64/*.so ./src/main/resources/linux-x86-64/
        mv ./linux-binary-aarch64/*.so ./src/main/resources/linux-aarch64/
        mv ./linux-binary-aarch64/*.so ./src/main/resources/linux-aarch64/
        mv ./linux-binary-x86-64/*.so.* ./src/main/resources/linux-x86-64/
        mv ./linux-binary-aarch64/*.so.* ./src/main/resources/linux-aarch64/
        mv ./linux-binary-aarch64/*.so.* ./src/main/resources/linux-aarch64/
        mv ./windows-binary-x86-64/*.dll ./src/main/resources/win-x86-64/
        mv ./mac-binary-x86-64/*.dylib ./src/main/resources/mac-x86-64/
        mv ./mac-binary-aarch64/*.dylib ./src/main/resources/mac-aarch64/
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'zulu'
        server-id: sonatype-nexus-staging
        server-username: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Deploy with Maven
      id: deploy
      run: |
        mvn -B clean deploy -DskipTests -Pci-cd
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        WHISPER_VERSION=$(echo "${VERSION%%"-"*}")
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "WHISPER_VERSION=$WHISPER_VERSION" >> $GITHUB_OUTPUT
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
    - name: Release
      uses: softprops/action-gh-release@v1
      id: create_release
      with:
        tag_name: whisper_jni_${{ steps.deploy.outputs.VERSION }}
        name: WhisperJNI v${{ steps.deploy.outputs.VERSION }}
        draft: false
        prerelease: false
        generate_release_notes: false
        body: A JNI wrapper over whisper.cpp v${{ steps.deploy.outputs.WHISPER_VERSION }}
        files: |
          target/whisper-jni-${{ steps.deploy.outputs.VERSION }}.jar
      env:
        GITHUB_TOKEN: ${{ github.token }}
