name: CI
on:
  workflow_dispatch:
jobs:
  download-models:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download tiny ggml model
      run: |
        git submodule update --init
        ./download-test-model.sh
        ./download-vad-model.sh
    - name: Artifact linux x64
      uses: actions/upload-artifact@v4
      with:
        name: tiny-ggml-model
        path: ggml-tiny.bin
        retention-days: 2
    - name: Upload silero model
      uses: actions/upload-artifact@v4
      with:
        name: silero-ggml-model
        path: ggml-silero-v5.1.2.bin
        retention-days: 2

  build-lib-linux-x64:
    needs: [download-models]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Setup project dir
        run: |
          mv ./tiny-ggml-model/ggml-tiny.bin ./ggml-tiny.bin
          mv ./silero-ggml-model/ggml-silero-v5.1.2.bin ./src/main/resources/ggml-silero-v5.1.2.bin
          mkdir -p dist
      - name: Build native library
        run: |
          docker build --build-arg="RUN_TESTS=true" -f dockerfile . -t whisperjni_binary:x64 --load
          docker run --platform=amd64 -v $(pwd)/dist:/out whisperjni_binary:x64 bash -c "cp src/main/resources/linux-x64/* /out/"
      - name: Artifact linux x64
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary-x64
          path: dist/*

  build-lib-linux-aarch64:
    needs: [download-models]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Setup project dir
        run: |
          mv ./tiny-ggml-model/ggml-tiny.bin ./ggml-tiny.bin
          mv ./silero-ggml-model/ggml-silero-v5.1.2.bin ./src/main/resources/ggml-silero-v5.1.2.bin
          mkdir -p dist
      - name: Build native library
        run: |
          docker build -f dockerfile . -t whisperjni_binary:aarch64 --platform arm64 --load
          DOCKER_BUILDKIT=1 docker run --platform=arm64 -v $(pwd)/dist:/out whisperjni_binary:aarch64 bash -c "cp src/main/resources/linux-aarch64/* /out/"
      - name: Artifact linux aarch64
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary-aarch64
          path: dist/*

  build-lib-windows-x64:
    needs: [download-models]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # - name: Set up Maven
      #   uses: stCarolas/setup-maven@v4.5
      #   with:
      #     maven-version: 3.9.2
      - name: Setup project dir
        run: |
          git submodule update --init
          mv ./tiny-ggml-model/ggml-tiny.bin ./ggml-tiny.bin
          mv ./silero-ggml-model/ggml-silero-v5.1.2.bin ./src/main/resources/ggml-silero-v5.1.2.bin
          mkdir dist
      - name: Build native library
        shell: powershell
        run: |
          .\build_win.ps1
          # mvn test
          mv src\main\resources\windows-x64\*.dll .\dist\
      - name: Artifact windows x64
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary-x64
          path: dist/*.dll

  build-lib-mac-x64:
    needs: [download-models]
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # - name: Set up Maven
      #   uses: stCarolas/setup-maven@v4.5
      #   with:
      #     maven-version: 3.9.2
      - name: Setup project dir
        run: |
          export DYLD_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/
          mkdir -p dist
          mkdir -p dist_aarch64
          git submodule update --init
          mv ./tiny-ggml-model/ggml-tiny.bin ./ggml-tiny.bin
          mv ./silero-ggml-model/ggml-silero-v5.1.2.bin ./src/main/resources/ggml-silero-v5.1.2.bin
      - name: Build binary
        run: |
          export DYLD_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/
          ./build_macos.sh x86-64
          # mvn test
          mv src/main/resources/mac-x64/*.dylib dist/
      - name: Artifact macos x64
        uses: actions/upload-artifact@v4
        with:
          name: mac-binary-x64
          path: dist/*.dylib
  
  build-lib-mac-aarch64:
    needs: [download-models]
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # - name: Set up Maven
      #   uses: stCarolas/setup-maven@v4.5
      #   with:
      #     maven-version: 3.9.2
      - name: Setup project dir
        run: |
          export DYLD_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/
          mkdir -p dist
          mkdir -p dist_aarch64
          git submodule update --init
          mv ./tiny-ggml-model/ggml-tiny.bin ./ggml-tiny.bin
          mv ./silero-ggml-model/ggml-silero-v5.1.2.bin ./src/main/resources/ggml-silero-v5.1.2.bin
      - name: Build binary
        run: |
          export DYLD_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/
          ./build_macos.sh aarch64
          # mvn test
          mv src/main/resources/mac-aarch64/*.dylib dist_aarch64/
      - name: Artifact macos aarch64
        uses: actions/upload-artifact@v4
        with:
          name: mac-binary-aarch64
          path: dist_aarch64/*.dylib

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-lib-linux-x64,build-lib-linux-aarch64,build-lib-windows-x64,build-lib-mac-x64, build-lib-mac-aarch64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
    - name: check tree
      run: ls -R
    - name: setup resources
      run: |
        mv ./linux-binary-x64/*.so ./src/main/resources/linux-x64/
        mv ./linux-binary-aarch64/*.so ./src/main/resources/linux-aarch64/
        mv ./linux-binary-aarch64/*.so ./src/main/resources/linux-aarch64/
        mv ./linux-binary-x64/*.so.* ./src/main/resources/linux-x64/
        mv ./linux-binary-aarch64/*.so.* ./src/main/resources/linux-aarch64/
        mv ./linux-binary-aarch64/*.so.* ./src/main/resources/linux-aarch64/
        mv ./windows-binary-x64/*.dll ./src/main/resources/windows-x64/
        mv ./mac-binary-x64/*.dylib ./src/main/resources/mac-x64/
        mv ./mac-binary-aarch64/*.dylib ./src/main/resources/mac-aarch64/
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v4
      with:
        java-version: 22
        distribution: 'temurin'
        server-id: sonatype-nexus-staging
        server-username: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Deploy with Maven
      id: deploy
      run: |
        ./gradlew build
    # I hope no one can see this
    - name: Upload JAR as private artifact
      uses: actions/upload-artifact@v4
      with:
        name: Whisper JNI
        path: build/libs/*.jar
